import type { Language } from '../../app/text';

export const domainText = {
  vi: {
    hello: 'Xin chào',
    welcome: 'Sổ tay dòng tiền sinh viên',
    overview: 'Tổng quan',
    history: 'Lịch sử',
    report: 'Báo cáo',
    mainNavigation: 'Điều hướng tài chính',
    logout: 'Đăng xuất',
    connectGoogle: 'Kết nối Google',
    googleConnected: 'Đã kết nối Google',
    balance: 'Số dư hiện tại',
    opening: 'Đầu kỳ',
    income: 'Thu nhập',
    payment: 'Thanh toán',
    closing: 'Cuối kỳ',
    savings: 'Tiết kiệm',
    moveSavings: 'Chuyển tiền tiết kiệm',
    deposit: 'Gửi vào khoản tiết kiệm',
    withdraw: 'Rút từ khoản tiết kiệm',
    transfer: 'Chuyển khoản',
    currentMonth: 'Tháng hiện tại',
    addTransaction: 'Ghi khoản mới',
    transactionType: 'Loại khoản tiền',
    amount: 'Số tiền (VND)',
    category: 'Danh mục',
    occurredAt: 'Thời gian',
    description: 'Ghi chú',
    descriptionHint: 'Ví dụ: Ăn trưa cùng bạn',
    save: 'Lưu khoản tiền',
    saving: 'Đang lưu...',
    requiredCategory: 'Chọn danh mục.',
    amountInvalid: 'Nhập số nguyên VND lớn hơn 0.',
    dateInvalid: 'Chọn ngày và giờ hợp lệ.',
    saved: 'Đã lưu. Số dư và báo cáo được làm mới từ máy chủ.',
    transactionOverrun: 'Đã lưu. Danh mục này đã vượt giới hạn ngân sách tháng.',
    loadError: 'Chưa tải được dữ liệu. Hãy thử tải lại.',
    retry: 'Thử lại',
    noTransactions: 'Chưa có khoản tiền nào được ghi.',
    recentTransactions: 'Giao dịch gần đây',
    allTransactions: 'Mọi khoản tiền được lưu theo thứ tự mới nhất.',
    transaction: 'Khoản tiền',
    date: 'Thời gian',
    type: 'Loại',
    amountColumn: 'Số tiền',
    loadMore: 'Tải thêm',
    loading: 'Đang tải...',
    chooseMonth: 'Chọn tháng',
    budgetTitle: 'Ngân sách tháng',
    setBudget: 'Đặt hoặc cập nhật ngân sách',
    budgetLimit: 'Giới hạn trong tháng (VND)',
    saveBudget: 'Lưu ngân sách',
    budgetTotal: 'Đã dùng / giới hạn',
    exceeded: 'Vượt giới hạn',
    withinBudget: 'Trong giới hạn',
    noBudgets: 'Tháng này chưa có ngân sách.',
    noReport: 'Chưa có báo cáo cho tháng này.',
    setOpening: 'Bắt đầu theo dõi số dư',
    openingHint: 'Nhập số tiền bạn đang có trước khi bắt đầu ghi thu và chi.',
    openingBalance: 'Số dư ban đầu (VND)',
    initialize: 'Bắt đầu ghi chép',
    initialized: 'Ví đã sẵn sàng.',
    transferSaved: 'Đã cập nhật ví và savings.',
    budgetSaved: 'Đã lưu ngân sách.',
    sessionExpired: 'Phiên đã hết hạn. Hãy đăng nhập lại.',
    reload: 'Làm mới dữ liệu',
    tableCaption: 'Danh sách giao dịch của tài khoản đang đăng nhập',
    emptyCategory: 'Không có danh mục phù hợp.',
    insufficient: 'Số dư hiện tại không đủ cho khoản thanh toán này.',
    insufficientSavings: 'Savings không đủ để rút khoản tiền này.',
    conflict: 'Yêu cầu này trùng với một lần gửi trước. Hãy tải lại dữ liệu trước khi thử lại.',
    categoryMismatch: 'Danh mục không phù hợp với loại khoản tiền đã chọn.',
    categoryDisabled: 'Danh mục này đã ngừng nhận khoản tiền mới.',
    alreadyInitialized: 'Ví đã được khởi tạo. Dữ liệu đã được làm mới.',
    serverError: 'Máy chủ đang bận. Thông tin đã nhập vẫn được giữ lại.',
    genericError: 'Không thể thực hiện yêu cầu. Thông tin đã nhập vẫn được giữ lại.',
    budgetOverrunCount: 'danh mục vượt giới hạn',
    categoryBreakdown: 'Khoản thanh toán theo danh mục',
    roleOriginal: 'Gốc',
    roleCorrection: 'Điều chỉnh',
  },
  en: {
    hello: 'Hello',
    welcome: 'Student cashbook',
    overview: 'Overview',
    history: 'History',
    report: 'Report',
    mainNavigation: 'Financial navigation',
    logout: 'Sign out',
    connectGoogle: 'Connect Google',
    googleConnected: 'Google connected',
    balance: 'Available balance',
    opening: 'Opening',
    income: 'Income',
    payment: 'Payment',
    closing: 'Closing',
    savings: 'Savings',
    moveSavings: 'Move money to savings',
    deposit: 'Deposit to savings',
    withdraw: 'Withdraw from savings',
    transfer: 'Transfer',
    currentMonth: 'Current month',
    addTransaction: 'Record a transaction',
    transactionType: 'Transaction type',
    amount: 'Amount (VND)',
    category: 'Category',
    occurredAt: 'Date and time',
    description: 'Note',
    descriptionHint: 'For example: Lunch with friends',
    save: 'Save transaction',
    saving: 'Saving...',
    requiredCategory: 'Choose a category.',
    amountInvalid: 'Enter a positive whole VND amount.',
    dateInvalid: 'Choose a valid date and time.',
    saved: 'Saved. Balance and report were refreshed from the server.',
    transactionOverrun: 'Saved. This category is over its monthly budget limit.',
    loadError: 'Could not load the data. Try again.',
    retry: 'Retry',
    noTransactions: 'No transactions have been recorded yet.',
    recentTransactions: 'Recent transactions',
    allTransactions: 'Transactions are shown newest first.',
    transaction: 'Transaction',
    date: 'Date and time',
    type: 'Type',
    amountColumn: 'Amount',
    loadMore: 'Load more',
    loading: 'Loading...',
    chooseMonth: 'Choose month',
    budgetTitle: 'Monthly budgets',
    setBudget: 'Set or update a budget',
    budgetLimit: 'Monthly limit (VND)',
    saveBudget: 'Save budget',
    budgetTotal: 'Used / limit',
    exceeded: 'Over limit',
    withinBudget: 'Within limit',
    noBudgets: 'There are no budgets for this month.',
    noReport: 'There is no report for this month.',
    setOpening: 'Set your starting balance',
    openingHint: 'Enter the money you have before you start recording income and payments.',
    openingBalance: 'Starting balance (VND)',
    initialize: 'Start tracking',
    initialized: 'Your wallet is ready.',
    transferSaved: 'Wallet and savings were updated.',
    budgetSaved: 'Budget saved.',
    sessionExpired: 'Your session expired. Please sign in again.',
    reload: 'Refresh data',
    tableCaption: 'Transactions for the signed-in account',
    emptyCategory: 'There are no matching categories.',
    insufficient: 'The available balance is not enough for this payment.',
    insufficientSavings: 'Savings do not have enough balance for this withdrawal.',
    conflict: 'This request conflicts with an earlier submission. Refresh before trying again.',
    categoryMismatch: 'This category does not match the selected transaction type.',
    categoryDisabled: 'This category no longer accepts new transactions.',
    alreadyInitialized: 'The wallet was already initialized. The data has been refreshed.',
    serverError: 'The server is busy. Your input has been kept.',
    genericError: 'The request could not be completed. Your input has been kept.',
    budgetOverrunCount: 'categories over limit',
    categoryBreakdown: 'Payments by category',
    roleOriginal: 'Original',
    roleCorrection: 'Correction',
  },
};

export function domainErrorText(code: string, language: Language) {
  const known: Record<string, keyof typeof domainText.vi> = {
    INSUFFICIENT_WALLET_BALANCE: 'insufficient',
    INSUFFICIENT_SAVINGS_BALANCE: 'insufficientSavings',
    IDEMPOTENCY_CONFLICT: 'conflict',
    CATEGORY_TYPE_MISMATCH: 'categoryMismatch',
    CATEGORY_DISABLED: 'categoryDisabled',
    WALLET_ALREADY_INITIALIZED: 'alreadyInitialized',
  };
  const key = known[code];
  return key ? domainText[language][key] : undefined;
}
