import type { Locale } from '../../types.js';

const vi = {
  title: 'Trung tâm vận hành', subtitle: 'Tiếp nhận và xử lý báo cáo, không thay đổi dữ liệu tài chính.',
  issues: 'Hàng đợi hỗ trợ', audit: 'Nhật ký kiểm toán', boundary: 'Không yêu cầu password, OTP, cookie, token hoặc toàn bộ ledger. Không sửa số dư hay giao dịch.',
  accounts: 'Tài khoản', accountNote: 'Danh sách đã mask email. Dừng tài khoản sẽ chặn đăng nhập và phiên; không xóa dữ liệu và không sửa ledger/balance.',
  email: 'Email (đã mask)', role: 'Vai trò', locale: 'Ngôn ngữ', status: 'Trạng thái', activeStatus: 'Đang hoạt động', disabledStatus: 'Đã dừng',
  active: 'active', disabled: 'disabled', disableAccount: 'Dừng tài khoản', enableAccount: 'Kích hoạt lại',
  disableTitle: 'Dừng tài khoản', disablePrompt: 'Nhập lý do bắt buộc; hành động này được ghi audit và không thể đảo ngược bằng UI.',
  enableTitle: 'Kích hoạt lại tài khoản', enablePrompt: 'Nhập lý do bắt buộc; hành động này được ghi audit.',
  reason: 'Lý do (bắt buộc)', reasonHint: 'Chỉ nhập lý do vận hành, không nhập secret hoặc PII không cần thiết.',
  reasonInvalid: 'Lý do phải từ 3 đến 500 ký tự.',
  confirmAction: 'Xác nhận', cancelAction: 'Hủy', statusChanged: 'Đã cập nhật trạng thái tài khoản.',
  selfChangeBlocked: 'Không thể dừng tài khoản đang thao tác.', unknownTarget: 'Không tìm thấy tài khoản.',
  statusColumn: 'Trạng thái', created: 'Ngày tạo',
  localeLabel: 'Ngôn ngữ', actionColumn: 'Hành động', selfBlocked: 'Tài khoản đang dùng',
  priority: 'Độ ưu tiên', all: 'Tất cả', titleColumn: 'Tiêu đề',
  open: 'Mới tiếp nhận', in_triage: 'Đang phân loại', resolved: 'Đã giải quyết', closed: 'Đã đóng',
  loaded: 'Báo cáo đã tải', urgent: 'P0 trong các báo cáo đã tải', triage: 'Đang phân loại trong các báo cáo đã tải',
  partial: 'Số liệu chỉ phản ánh các trang đã tải theo bộ lọc, không phải tổng toàn hệ thống.',
  empty: 'Không có báo cáo khớp bộ lọc.', refresh: 'Làm mới', detail: 'Xem chi tiết', save: 'Lưu phân loại', saved: 'Đã lưu phân loại.',
  note: 'Note nội bộ', noteHint: 'Note được thêm append-only. Không nhập secret, PII hoặc chi tiết tài chính không cần thiết.',
  addNote: 'Thêm note', noteSaved: 'Đã thêm note.', noteInvalid: 'Nhập note từ 1 đến 4.000 ký tự.',
  noteRetry: 'Chưa xác định note đã được lưu hay chưa. Thử lại với cùng nội dung để tránh trùng note.',
  incident: 'P0: nghi IDOR, lộ dữ liệu hoặc sai invariant. Escalate ngay cho Security/owner; không sửa ledger trực tiếp.',
  assignment: 'Phân công owner chưa được hỗ trợ bởi API hiện tại. Escalate theo quy trình vận hành ngoài ứng dụng.',
  readOnly: 'Audit chỉ đọc, không được sửa hoặc xóa.', action: 'Hành động', outcome: 'Kết quả', success: 'Thành công', failure: 'Thất bại',
  denied: 'Chỉ tài khoản admin được truy cập. Quyền vẫn được kiểm tra tại server.', emptyAudit: 'Chưa có sự kiện audit.',
  emptyAccounts: 'Chưa có tài khoản phù hợp.',
  metrics: 'Chỉ số vận hành', metricsNote: 'Chỉ dùng aggregate từ users, issues và audit — không hiển thị tổng tiền của user.',
  metricsUsers: 'Tài khoản', metricsIssues: 'Báo cáo', metricsAudit: 'Kiểm toán',
  totalUsers: 'Tổng tài khoản', verifiedUsers: 'Đã xác minh', activeUsers: 'Đang hoạt động', disabledUsers: 'Đã dừng',
  totalIssues: 'Tổng báo cáo', openTotal: 'Mở', inTriageTotal: 'Đang phân loại', resolvedTotal: 'Đã giải quyết', closedTotal: 'Đã đóng',
  p0Total: 'P0', p1Total: 'P1', p2Total: 'P2', auditSuccess: 'Thành công', auditFailure: 'Thất bại',
};
const en: typeof vi = {
  title: 'Operations center', subtitle: 'Review and triage reports without changing financial records.',
  issues: 'Support queue', audit: 'Audit log', boundary: 'Never request passwords, OTPs, cookies, tokens or a full ledger. Do not edit balances or transactions.',
  accounts: 'Accounts', accountNote: 'Emails are masked. Disabling an account blocks login and sessions; it never deletes data or edits ledger/balance.',
  email: 'Email (masked)', role: 'Role', locale: 'Language', status: 'Status', activeStatus: 'Active', disabledStatus: 'Disabled',
  active: 'active', disabled: 'disabled', disableAccount: 'Disable account', enableAccount: 'Reactivate account',
  disableTitle: 'Disable account', disablePrompt: 'A reason is required; this action is audited and cannot be undone from the UI.',
  enableTitle: 'Reactivate account', enablePrompt: 'A reason is required; this action is audited.',
  reason: 'Reason (required)', reasonHint: 'Enter an operational reason only; do not enter secrets or unnecessary PII.',
  reasonInvalid: 'Reason must be 3-500 characters.',
  confirmAction: 'Confirm', cancelAction: 'Cancel', statusChanged: 'Account status updated.',
  selfChangeBlocked: 'You cannot disable the account you are currently using.', unknownTarget: 'Account not found.',
  statusColumn: 'Status', created: 'Created',
  localeLabel: 'Language', actionColumn: 'Action', selfBlocked: 'Current account',
  priority: 'Priority', all: 'All', titleColumn: 'Title',
  open: 'Open', in_triage: 'In triage', resolved: 'Resolved', closed: 'Closed',
  loaded: 'Loaded reports', urgent: 'P0 among loaded reports', triage: 'In triage among loaded reports',
  partial: 'Counts cover loaded pages under the current filters, not system-wide totals.',
  empty: 'No reports match these filters.', refresh: 'Refresh', detail: 'View details', save: 'Save triage', saved: 'Triage saved.',
  note: 'Internal note', noteHint: 'Notes are append-only. Do not enter secrets, PII or unnecessary financial details.',
  addNote: 'Add note', noteSaved: 'Note added.', noteInvalid: 'Enter a note between 1 and 4,000 characters.',
  noteRetry: 'The note save outcome is uncertain. Retry the same content to avoid duplicate notes.',
  incident: 'P0: suspected IDOR, data exposure or invariant failure. Escalate immediately to Security/owner; never edit the ledger directly.',
  assignment: 'Owner assignment is not supported by the current API. Escalate using the external operations workflow.',
  readOnly: 'Audit is read-only and cannot be edited or deleted.', action: 'Action', outcome: 'Outcome', success: 'Success', failure: 'Failure',
  denied: 'Only admin accounts can access this area. The server also enforces permissions.', emptyAudit: 'No audit events yet.',
  emptyAccounts: 'No matching accounts yet.',
  metrics: 'Operations metrics', metricsNote: 'Aggregates from users, issues and audit only — no user money totals.',
  metricsUsers: 'Accounts', metricsIssues: 'Reports', metricsAudit: 'Audit',
  totalUsers: 'Total accounts', verifiedUsers: 'Verified', activeUsers: 'Active', disabledUsers: 'Disabled',
  totalIssues: 'Total reports', openTotal: 'Open', inTriageTotal: 'In triage', resolvedTotal: 'Resolved', closedTotal: 'Closed',
  p0Total: 'P0', p1Total: 'P1', p2Total: 'P2', auditSuccess: 'Success', auditFailure: 'Failure',
};
export const adminCopy: Record<Locale, typeof vi> = { vi, en };
