/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bắt đầu Google OAuth */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect tới Google OAuth consent */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Xử lý callback Google OAuth */
        get: {
            parameters: {
                query: {
                    code: components["parameters"]["OAuthCode"];
                    state: components["parameters"]["OAuthState"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect tới onboarding hoặc dashboard; response đặt session cookie */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["InvalidOAuthState"];
                401: components["responses"]["UnverifiedEmail"];
                500: components["responses"]["OAuthExchangeFailed"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy session hiện tại và trạng thái onboarding */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session hợp lệ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["AccountDisabled"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke session hiện tại */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session đã revoke và cookie được clear */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật preference người dùng */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePreferencesRequest"];
                };
            };
            responses: {
                /** @description Preference đã cập nhật */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy wallet authoritative của user hiện tại */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Wallet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WalletResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Khởi tạo opening wallet balance một lần */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WalletBaselineRequest"];
                };
            };
            responses: {
                /** @description Wallet đã khởi tạo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WalletResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                409: components["responses"]["WalletAlreadyInitialized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê ledger transaction của user hiện tại */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    type?: components["schemas"]["TransactionType"];
                    categoryId?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ledger page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionPageResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        /** Tạo income hoặc payment immutable */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTransactionRequest"];
                };
            };
            responses: {
                /** @description Transaction đã commit */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                409: components["responses"]["IdempotencyConflict"];
                422: components["responses"]["DomainValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/transactions/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy một transaction */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transaction */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/transactions/{transactionId}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo correction append-only */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCorrectionRequest"];
                };
            };
            responses: {
                /** @description Correction đã commit */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["DomainValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy savings aggregate */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Savings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavingsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê savings transfer */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Savings transfer page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavingsTransferPageResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Gửi hoặc rút savings atomic */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSavingsTransferRequest"];
                };
            };
            responses: {
                /** @description Transfer đã commit */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavingsTransferResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                409: components["responses"]["IdempotencyConflict"];
                422: components["responses"]["DomainValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê category system và user */
        get: {
            parameters: {
                query?: {
                    appliesTo?: components["schemas"]["TransactionType"];
                    includeDisabled?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Tạo custom category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCategoryRequest"];
                };
            };
            responses: {
                /** @description Category đã tạo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Đổi tên hoặc disable custom category */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryId: components["parameters"]["CategoryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCategoryRequest"];
                };
            };
            responses: {
                /** @description Category đã cập nhật */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy budget theo tháng HCMC */
        get: {
            parameters: {
                query: {
                    /** @example 2026-09 */
                    month: components["parameters"]["Month"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Budget list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Tạo hoặc thay thế budget payment category theo tháng */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryId: components["parameters"]["CategoryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertBudgetRequest"];
                };
            };
            responses: {
                /** @description Budget đã cập nhật */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["DomainValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy tổng quan budget theo tháng */
        get: {
            parameters: {
                query: {
                    /** @example 2026-09 */
                    month: components["parameters"]["Month"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Budget summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetSummaryResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Báo cáo deterministic theo tháng HCMC */
        get: {
            parameters: {
                query: {
                    /** @example 2026-09 */
                    month: components["parameters"]["Month"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monthly report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyReportResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot dashboard authoritative */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo issue hỗ trợ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIssueRequest"];
                };
            };
            responses: {
                /** @description Issue đã tạo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssueResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê issue của user hiện tại */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Issue page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssuePageResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Triage issue toàn hệ thống */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: components["schemas"]["IssueStatus"];
                    priority?: components["schemas"]["IssuePriority"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin issue page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssuePageResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy issue và timeline đã mask */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    issueId: components["parameters"]["IssueId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Issue detail and timeline */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminIssueDetailResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật status hoặc priority issue */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    issueId: components["parameters"]["IssueId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateIssueRequest"];
                };
            };
            responses: {
                /** @description Issue đã cập nhật */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssueResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/admin/issues/{issueId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Thêm admin note append-only */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    issueId: components["parameters"]["IssueId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAdminNoteRequest"];
                };
            };
            responses: {
                /** @description Note đã tạo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssueEventResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Truy vấn audit đã redact */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditPageResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/category-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gợi ý category trước submit, luôn advisory */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategorySuggestionRequest"];
                };
            };
            responses: {
                /** @description JEV suggestion hoặc manual/disabled fallback */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategorySuggestionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["CsrfInvalid"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness không chạm database */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API đang chạy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness có kiểm tra dependency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dependency sẵn sàng */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TransactionType: "income" | "payment";
        /** @enum {string} */
        Locale: "en" | "vi";
        /** @description Số nguyên VND; không dùng floating point */
        MoneyVnd: number;
        /** @description Số nguyên VND dương */
        PositiveMoneyVnd: number;
        User: {
            id: string;
            displayName: string;
            /** Format: email */
            email: string;
            locale: components["schemas"]["Locale"];
            /** @enum {string} */
            role: "user" | "admin" | "security";
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        Session: {
            user: components["schemas"]["User"];
            walletInitialized: boolean;
            /** @description Token dùng trong memory cho state-changing request */
            csrfToken: string;
        };
        SessionResponse: {
            data: components["schemas"]["Session"];
        };
        UpdatePreferencesRequest: {
            displayName?: string;
            locale?: components["schemas"]["Locale"];
        };
        Wallet: {
            walletId: string;
            initialized: boolean;
            initialBalanceVnd: components["schemas"]["MoneyVnd"];
            availableBalanceVnd: components["schemas"]["MoneyVnd"];
            /** @constant */
            currency: "VND";
            /** Format: date-time */
            updatedAt: string;
        };
        WalletResponse: {
            data: components["schemas"]["Wallet"];
        };
        WalletBaselineRequest: {
            initialBalanceVnd: components["schemas"]["MoneyVnd"];
        };
        CreateTransactionRequest: {
            type: components["schemas"]["TransactionType"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            categoryId: string;
            /** Format: date-time */
            occurredAt: string;
            description?: string;
            /** @default false */
            confirmedCategorySuggestion: boolean;
        };
        /** @enum {string} */
        CorrectionRole: "reversal" | "adjustment" | "replacement";
        /** @enum {string} */
        TransactionRole: "original" | "reversal" | "adjustment" | "replacement";
        CreateCorrectionRequest: {
            correctionRole: components["schemas"]["CorrectionRole"];
            reason: string;
            newAmountVnd?: components["schemas"]["PositiveMoneyVnd"];
            newCategoryId?: string;
        };
        Transaction: {
            id: string;
            type: components["schemas"]["TransactionType"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            categoryId: string;
            /** Format: date-time */
            occurredAt: string;
            description?: string | null;
            role: components["schemas"]["TransactionRole"];
            referenceId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        BudgetWarning: {
            isOverrun: boolean;
            limitVnd: components["schemas"]["MoneyVnd"];
            usedVnd: components["schemas"]["MoneyVnd"];
        };
        TransactionResponse: {
            data: {
                transaction: components["schemas"]["Transaction"];
                budgetWarning?: components["schemas"]["BudgetWarning"];
            };
        };
        PageMeta: {
            cursor?: string | null;
            hasNext: boolean;
        };
        TransactionPageResponse: {
            data: components["schemas"]["Transaction"][];
            meta: components["schemas"]["PageMeta"];
        };
        Savings: {
            balanceVnd: components["schemas"]["MoneyVnd"];
            /** @constant */
            currency: "VND";
            /** Format: date-time */
            updatedAt: string;
        };
        SavingsResponse: {
            data: components["schemas"]["Savings"];
        };
        /** @enum {string} */
        TransferDirection: "deposit" | "withdraw";
        CreateSavingsTransferRequest: {
            direction: components["schemas"]["TransferDirection"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            note?: string;
        };
        SavingsTransfer: {
            id: string;
            direction: components["schemas"]["TransferDirection"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            note?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        SavingsTransferResponse: {
            data: components["schemas"]["SavingsTransfer"];
        };
        SavingsTransferPageResponse: {
            data: components["schemas"]["SavingsTransfer"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** @enum {string} */
        CategoryStatus: "active" | "disabled" | "retired";
        Category: {
            id: string;
            name: {
                en: string;
                vi: string;
            };
            appliesTo: components["schemas"]["TransactionType"];
            status: components["schemas"]["CategoryStatus"];
            isDefault: boolean;
        };
        CategoryResponse: {
            data: components["schemas"]["Category"];
        };
        CategoryListResponse: {
            data: components["schemas"]["Category"][];
        };
        CreateCategoryRequest: {
            nameEn: string;
            nameVi?: string;
            appliesTo: components["schemas"]["TransactionType"];
        };
        UpdateCategoryRequest: {
            nameEn?: string;
            nameVi?: string;
            status?: components["schemas"]["CategoryStatus"];
        };
        Budget: {
            categoryId: string;
            month: string;
            limitVnd: components["schemas"]["MoneyVnd"];
            usedVnd: components["schemas"]["MoneyVnd"];
            isOverrun: boolean;
        };
        BudgetResponse: {
            data: components["schemas"]["Budget"];
        };
        BudgetListResponse: {
            data: components["schemas"]["Budget"][];
        };
        UpsertBudgetRequest: {
            month: string;
            limitVnd: components["schemas"]["MoneyVnd"];
        };
        BudgetSummary: {
            month: string;
            totalLimitVnd: components["schemas"]["MoneyVnd"];
            totalUsedVnd: components["schemas"]["MoneyVnd"];
            exceededCategoryCount: number;
        };
        BudgetSummaryResponse: {
            data: components["schemas"]["BudgetSummary"];
        };
        MonthlyReport: {
            month: string;
            openingWalletBalanceVnd: components["schemas"]["MoneyVnd"];
            totalIncomeVnd: components["schemas"]["MoneyVnd"];
            totalPaymentVnd: components["schemas"]["MoneyVnd"];
            closingWalletBalanceVnd: components["schemas"]["MoneyVnd"];
            categoryBreakdown: components["schemas"]["CategoryTotal"][];
        };
        CategoryTotal: {
            categoryId: string;
            amountVnd: components["schemas"]["MoneyVnd"];
        };
        MonthlyReportResponse: {
            data: components["schemas"]["MonthlyReport"];
        };
        Dashboard: {
            wallet: components["schemas"]["Wallet"];
            savings: components["schemas"]["Savings"];
            currentMonth: components["schemas"]["MonthlyReport"];
            recentTransactions: components["schemas"]["Transaction"][];
        };
        DashboardResponse: {
            data: components["schemas"]["Dashboard"];
        };
        /** @enum {string} */
        IssueStatus: "open" | "in_triage" | "resolved" | "closed";
        /** @enum {string} */
        IssuePriority: "P0" | "P1" | "P2";
        Issue: {
            id: string;
            title: string;
            description?: string;
            status: components["schemas"]["IssueStatus"];
            priority: components["schemas"]["IssuePriority"];
            /** Format: date-time */
            createdAt: string;
        };
        IssueResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["Issue"];
            meta: null;
        };
        IssuePageResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["Issue"][];
            meta: components["schemas"]["PageMeta"];
        };
        IssueEvent: {
            id: string;
            /** @enum {string} */
            kind: "created" | "reporter_update" | "status_change" | "priority_change" | "note";
            note?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AdminIssueDetailResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["Issue"] & {
                events: components["schemas"]["IssueEvent"][];
            };
            meta: null;
        };
        IssueEventResponse: {
            /** @constant */
            success: true;
            data: {
                id: string;
                /** Format: date-time */
                createdAt: string;
            };
            meta: null;
        };
        CreateIssueRequest: {
            title: string;
            description: string;
            /** @enum {string} */
            category: "financial_dispute" | "bug" | "other";
            relatedTransactionId?: string;
        };
        UpdateIssueRequest: {
            status?: components["schemas"]["IssueStatus"];
            priority?: components["schemas"]["IssuePriority"];
        };
        CreateAdminNoteRequest: {
            note: string;
        };
        AuditEvent: {
            id: string;
            action: string;
            outcome: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditPageResponse: {
            data: components["schemas"]["AuditEvent"][];
            meta: components["schemas"]["PageMeta"];
        };
        CategorySuggestionRequest: {
            transactionType: components["schemas"]["TransactionType"];
            description: string;
            locale: components["schemas"]["Locale"];
        };
        CategorySuggestion: {
            /** @enum {string} */
            status: "suggested" | "manual" | "disabled" | "unavailable";
            categoryId: string | null;
            confidence: number | null;
            /** @enum {string|null} */
            reasonCode: "low_confidence" | "timeout" | "quota" | "schema" | "flag_off" | "privacy" | null;
        };
        CategorySuggestionResponse: {
            data: components["schemas"]["CategorySuggestion"];
        };
        Health: {
            /** @constant */
            status: "pass";
            /** Format: date-time */
            timestamp: string;
        };
        HealthResponse: {
            data: components["schemas"]["Health"];
        };
        Readiness: {
            /** @enum {string} */
            status: "pass" | "fail";
            checks: {
                [key: string]: string;
            };
        };
        ReadinessResponse: {
            data: components["schemas"]["Readiness"];
        };
        ErrorDetail: {
            field?: string;
            code: string;
            message: string;
        };
        ApiError: {
            code: string;
            message: string;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorResponse: {
            /** @constant */
            success: false;
            data: null;
            error: components["schemas"]["ApiError"];
            meta: null;
        };
    };
    responses: {
        /** @description Thiếu, hết hạn hoặc bị revoke session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Tài khoản bị disable */
        AccountDisabled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description CSRF hoặc Origin không hợp lệ */
        CsrfInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Không đủ quyền */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Không tìm thấy resource hoặc resource ngoài owner scope */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Xung đột state hoặc uniqueness */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Idempotency key đã dùng với body khác */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Input không hợp lệ */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Vi phạm domain hoặc invariant */
        DomainValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Vượt rate limit */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Lỗi server đã được sanitize */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description OAuth state/PKCE không hợp lệ */
        InvalidOAuthState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Google email chưa verified */
        UnverifiedEmail: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Code exchange hoặc claim validation thất bại */
        OAuthExchangeFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Wallet đã khởi tạo */
        WalletAlreadyInitialized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Dependency chưa sẵn sàng */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OAuthCode: string;
        OAuthState: string;
        Cursor: string;
        Limit: number;
        /** @example 2026-09 */
        Month: string;
        TransactionId: string;
        CategoryId: string;
        IssueId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
