/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gửi OTP để bắt đầu đăng ký bằng email */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xác minh OTP và tạo tài khoản bằng email, họ tên, mật khẩu */
        post: operations["postAuthVerifyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gửi lại mã OTP */
        post: operations["postAuthResendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập email và mật khẩu */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy các phương thức đăng nhập đang được cấu hình */
        get: operations["getAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bắt đầu Google Sign-In bằng OAuth Authorization Code và PKCE */
        get: operations["getAuthGoogleStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bắt đầu kết nối Google từ tài khoản đã đăng nhập */
        post: operations["postAuthGoogleLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hoàn tất callback OIDC Google và chuyển về ứng dụng */
        get: operations["getAuthGoogleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yêu cầu OTP đặt lại mật khẩu */
        post: operations["postAuthForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đặt lại mật khẩu với OTP */
        post: operations["postAuthResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy CSRF token */
        get: operations["getAuthCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin user hiện tại (owner scope) */
        get: operations["getUsersMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin user theo ID (chống IDOR - chỉ cho phép lấy id của chính mình) */
        get: operations["getUsersByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy người dùng và CSRF token của phiên hiện tại */
        get: operations["getAuthSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke session hiện tại; yêu cầu CSRF khi phiên còn hiệu lực, thao tác lặp là idempotent */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật preference người dùng */
        patch: operations["patchUsersMePreferences"];
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy wallet authoritative của user hiện tại */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Khởi tạo opening wallet balance một lần */
        post: operations["postWalletBaseline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê ledger transaction của user hiện tại */
        get: operations["getLedgerTransactions"];
        put?: never;
        /** Tạo income hoặc payment immutable */
        post: operations["postLedgerTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/transactions/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy một transaction */
        get: operations["getLedgerTransactionsByTransactionId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/transactions/{transactionId}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo correction append-only */
        post: operations["postLedgerTransactionsByTransactionIdCorrections"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy savings aggregate */
        get: operations["getSavings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê savings transfer */
        get: operations["getSavingsTransfers"];
        put?: never;
        /** Gửi hoặc rút savings atomic */
        post: operations["postSavingsTransfers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê category system và user */
        get: operations["getCategories"];
        put?: never;
        /** Tạo custom category */
        post: operations["postCategories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Đổi tên hoặc disable custom category */
        patch: operations["patchCategoriesByCategoryId"];
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy budget theo tháng HCMC */
        get: operations["getBudgets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Tạo hoặc thay thế budget payment category theo tháng */
        put: operations["putBudgetsByCategoryId"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy tổng quan budget theo tháng */
        get: operations["getBudgetsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Báo cáo deterministic theo tháng HCMC */
        get: operations["getReportsMonthly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot dashboard authoritative */
        get: operations["getReportsDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo issue hỗ trợ */
        post: operations["postIssues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liệt kê issue của user hiện tại */
        get: operations["getIssuesMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Triage issue toàn hệ thống */
        get: operations["getAdminIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy issue và timeline đã mask */
        get: operations["getAdminIssuesByIssueId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật status hoặc priority issue */
        patch: operations["patchAdminIssuesByIssueId"];
        trace?: never;
    };
    "/admin/issues/{issueId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Thêm admin note append-only */
        post: operations["postAdminIssuesByIssueIdNotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Truy vấn audit đã redact */
        get: operations["getAdminAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê số lượng user đã xác minh */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness không chạm database */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness có kiểm tra dependency */
        get: operations["getHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TransactionType: "income" | "payment";
        /** @enum {string} */
        Locale: "en" | "vi";
        /** @description Số nguyên VND trong miền integer an toàn của JavaScript; không dùng floating point */
        MoneyVnd: number;
        /** @description Số nguyên VND dương trong miền integer an toàn của JavaScript */
        PositiveMoneyVnd: number;
        User: {
            id: string;
            displayName: string;
            /** Format: email */
            email: string;
            locale: components["schemas"]["Locale"];
            /** @enum {string} */
            role: "user" | "admin" | "security";
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        Session: {
            user: components["schemas"]["User"];
            /** @description Token dùng trong memory cho state-changing request */
            csrfToken: string;
            /** @description Cho biết tài khoản hiện tại đã kết nối Google hay chưa */
            googleLinked: boolean;
        };
        SessionResponse: {
            data: components["schemas"]["Session"];
        };
        AuthProvidersResponse: {
            data: {
                google: boolean;
            };
        };
        GoogleLinkStartResponse: {
            data: {
                /** Format: uri */
                url: string;
            };
        };
        UpdatePreferencesRequest: {
            displayName?: string;
            locale?: components["schemas"]["Locale"];
        };
        Wallet: {
            walletId: string;
            initialized: boolean;
            initialBalanceVnd: components["schemas"]["MoneyVnd"];
            availableBalanceVnd: components["schemas"]["MoneyVnd"];
            /** @constant */
            currency: "VND";
            /** Format: date-time */
            updatedAt: string;
        };
        WalletResponse: {
            data: components["schemas"]["Wallet"];
        };
        WalletBaselineRequest: {
            initialBalanceVnd: components["schemas"]["MoneyVnd"];
        };
        CreateTransactionRequest: {
            type: components["schemas"]["TransactionType"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            categoryId: string;
            /** Format: date-time */
            occurredAt: string;
            description?: string;
            /** @default false */
            confirmedCategorySuggestion: boolean;
        };
        /** @enum {string} */
        CorrectionRole: "reversal" | "adjustment" | "replacement";
        /** @enum {string} */
        TransactionRole: "original" | "reversal" | "adjustment" | "replacement";
        CreateCorrectionRequest: {
            correctionRole: components["schemas"]["CorrectionRole"];
            reason: string;
            newAmountVnd?: components["schemas"]["PositiveMoneyVnd"];
            newCategoryId?: string;
        };
        Transaction: {
            id: string;
            type: components["schemas"]["TransactionType"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            categoryId: string;
            /** Format: date-time */
            occurredAt: string;
            description?: string | null;
            role: components["schemas"]["TransactionRole"];
            referenceId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        BudgetWarning: {
            isOverrun: boolean;
            limitVnd: components["schemas"]["MoneyVnd"];
            usedVnd: components["schemas"]["MoneyVnd"];
        };
        TransactionResponse: {
            data: {
                transaction: components["schemas"]["Transaction"];
                budgetWarning?: components["schemas"]["BudgetWarning"];
            };
        };
        PageMeta: {
            cursor?: string | null;
            hasNext: boolean;
        };
        TransactionPageResponse: {
            data: components["schemas"]["Transaction"][];
            meta: components["schemas"]["PageMeta"];
        };
        Savings: {
            balanceVnd: components["schemas"]["MoneyVnd"];
            /** @constant */
            currency: "VND";
            /** Format: date-time */
            updatedAt: string;
        };
        SavingsResponse: {
            data: components["schemas"]["Savings"];
        };
        /** @enum {string} */
        TransferDirection: "deposit" | "withdraw";
        CreateSavingsTransferRequest: {
            direction: components["schemas"]["TransferDirection"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            note?: string;
        };
        SavingsTransfer: {
            id: string;
            direction: components["schemas"]["TransferDirection"];
            amountVnd: components["schemas"]["PositiveMoneyVnd"];
            note?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        SavingsTransferResponse: {
            data: components["schemas"]["SavingsTransfer"];
        };
        SavingsTransferPageResponse: {
            data: components["schemas"]["SavingsTransfer"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** @enum {string} */
        CategoryStatus: "active" | "disabled" | "retired";
        Category: {
            id: string;
            name: {
                en: string;
                vi: string;
            };
            appliesTo: components["schemas"]["TransactionType"];
            status: components["schemas"]["CategoryStatus"];
            isDefault: boolean;
        };
        CategoryResponse: {
            data: components["schemas"]["Category"];
        };
        CategoryListResponse: {
            data: components["schemas"]["Category"][];
        };
        CreateCategoryRequest: {
            nameEn: string;
            nameVi?: string;
            appliesTo: components["schemas"]["TransactionType"];
        };
        UpdateCategoryRequest: {
            nameEn?: string;
            nameVi?: string;
            status?: components["schemas"]["CategoryStatus"];
        };
        Budget: {
            categoryId: string;
            month: string;
            limitVnd: components["schemas"]["MoneyVnd"];
            usedVnd: components["schemas"]["MoneyVnd"];
            isOverrun: boolean;
        };
        BudgetResponse: {
            data: components["schemas"]["Budget"];
        };
        BudgetListResponse: {
            data: components["schemas"]["Budget"][];
        };
        UpsertBudgetRequest: {
            month: string;
            limitVnd: components["schemas"]["MoneyVnd"];
        };
        BudgetSummary: {
            month: string;
            totalLimitVnd: components["schemas"]["MoneyVnd"];
            totalUsedVnd: components["schemas"]["MoneyVnd"];
            exceededCategoryCount: number;
        };
        BudgetSummaryResponse: {
            data: components["schemas"]["BudgetSummary"];
        };
        MonthlyReport: {
            month: string;
            openingWalletBalanceVnd: components["schemas"]["MoneyVnd"];
            totalIncomeVnd: components["schemas"]["MoneyVnd"];
            totalPaymentVnd: components["schemas"]["MoneyVnd"];
            closingWalletBalanceVnd: components["schemas"]["MoneyVnd"];
            categoryBreakdown: components["schemas"]["CategoryTotal"][];
        };
        CategoryTotal: {
            categoryId: string;
            amountVnd: components["schemas"]["MoneyVnd"];
        };
        MonthlyReportResponse: {
            data: components["schemas"]["MonthlyReport"];
        };
        Dashboard: {
            wallet: components["schemas"]["Wallet"];
            savings: components["schemas"]["Savings"];
            currentMonth: components["schemas"]["MonthlyReport"];
            recentTransactions: components["schemas"]["Transaction"][];
        };
        DashboardResponse: {
            data: components["schemas"]["Dashboard"];
        };
        /** @enum {string} */
        IssueStatus: "open" | "in_triage" | "resolved" | "closed";
        /** @enum {string} */
        IssuePriority: "P0" | "P1" | "P2";
        Issue: {
            id: string;
            title: string;
            description?: string;
            /** @enum {string} */
            category?: "financial_dispute" | "bug" | "other";
            relatedTransactionId?: string | null;
            status: components["schemas"]["IssueStatus"];
            priority: components["schemas"]["IssuePriority"];
            /** Format: date-time */
            createdAt: string;
            events?: components["schemas"]["IssueEvent"][];
        };
        IssueEvent: {
            /** @enum {string} */
            kind: "created" | "status_change" | "priority_change" | "note";
            note?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        IssueResponse: {
            data: components["schemas"]["Issue"];
        };
        IssuePageResponse: {
            data: components["schemas"]["Issue"][];
            meta: components["schemas"]["PageMeta"];
        };
        CreateIssueRequest: {
            title: string;
            description: string;
            /** @enum {string} */
            category: "financial_dispute" | "bug" | "other";
            relatedTransactionId?: string;
        };
        UpdateIssueRequest: {
            status?: components["schemas"]["IssueStatus"];
            priority?: components["schemas"]["IssuePriority"];
        };
        CreateAdminNoteRequest: {
            note: string;
        };
        AdminNoteResult: {
            issueId: string;
            created: boolean;
        };
        AdminNoteResponse: {
            data: components["schemas"]["AdminNoteResult"];
        };
        AdminStats: {
            totalUsers: number;
            verifiedUsers: number;
        };
        AdminStatsResponse: {
            data: components["schemas"]["AdminStats"];
        };
        AuditEvent: {
            id: string;
            action: string;
            outcome: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditPageResponse: {
            data: components["schemas"]["AuditEvent"][];
            meta: components["schemas"]["PageMeta"];
        };
        Health: {
            /** @constant */
            status: "pass";
            /** Format: date-time */
            timestamp: string;
        };
        HealthResponse: {
            data: components["schemas"]["Health"];
        };
        Readiness: {
            /** @enum {string} */
            status: "pass" | "fail";
            checks: {
                [key: string]: string;
            };
        };
        ReadinessResponse: {
            data: components["schemas"]["Readiness"];
        };
        ErrorDetail: {
            field?: string;
            code: string;
            message: string;
        };
        ApiError: {
            code: string;
            message: string;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorResponse: {
            error: components["schemas"]["ApiError"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
        };
        VerifyRegistrationRequest: {
            /** Format: email */
            email: string;
            otp: string;
            fullName: string;
            password: string;
            locale?: components["schemas"]["Locale"];
        };
        ResendOtpRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            purpose: "registration" | "password_reset";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            /** Format: email */
            email: string;
            otp: string;
            newPassword: string;
        };
        MessageResponse: {
            data: {
                message: string;
            };
        };
        CsrfTokenResponse: {
            data: {
                csrfToken: string;
            };
        };
    };
    responses: {
        /** @description Request body JSON không hợp lệ */
        BadRequest: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request vượt giới hạn kích thước */
        PayloadTooLarge: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Thiếu, hết hạn hoặc bị revoke session */
        Unauthorized: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin không hợp lệ, tài khoản bị vô hiệu hoặc email chưa xác minh */
        LoginForbidden: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin của request không được phép */
        OriginInvalid: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin không hợp lệ hoặc CSRF token thiếu/sai; error code trong body phân biệt hai trường hợp */
        CsrfInvalid: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Không đủ quyền */
        Forbidden: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Không tìm thấy resource hoặc resource ngoài owner scope */
        NotFound: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Xung đột state hoặc uniqueness */
        Conflict: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Idempotency key đã dùng với body khác */
        IdempotencyConflict: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Input không hợp lệ */
        ValidationError: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Vi phạm domain hoặc invariant */
        DomainValidationError: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Vượt rate limit */
        RateLimited: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Lỗi server đã được sanitize */
        InternalError: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Wallet đã khởi tạo */
        WalletAlreadyInitialized: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Dependency chưa sẵn sàng */
        ServiceUnavailable: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        /** @example 2026-09 */
        Month: string;
        TransactionId: string;
        CategoryId: string;
        IssueId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Không lưu response riêng tư trong browser hoặc shared cache. */
        PrivateNoStore: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Mã OTP đã gửi; tài khoản chưa được tạo */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginInvalid"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
            default: components["responses"]["InternalError"];
        };
    };
    postAuthVerifyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRegistrationRequest"];
            };
        };
        responses: {
            /** @description Xác minh thành công */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginInvalid"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postAuthResendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendOtpRequest"];
            };
        };
        responses: {
            /** @description OTP đã gửi lại */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginInvalid"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
            default: components["responses"]["InternalError"];
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Đăng nhập thành công, thiết lập session cookie */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["LoginForbidden"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phương thức hiện có */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProvidersResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAuthGoogleStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chuyển trình duyệt đến Google; cookie flow ngắn hạn được thiết lập */
            302: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    Location?: string;
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lỗi chuyển hướng đã được xử lý an toàn */
            default: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postAuthGoogleLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL xác thực Google và cookie flow */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleLinkStartResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
            default: components["responses"]["InternalError"];
        };
    };
    getAuthGoogleCallback: {
        parameters: {
            query: {
                state: string;
                code?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chuyển về ứng dụng; thiết lập session khi đăng nhập thành công */
            302: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    Location?: string;
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lỗi callback được chuyển về ứng dụng bằng mã lỗi an toàn */
            default: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postAuthForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Phản hồi tiêu chuẩn không để lộ sự tồn tại của email */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginInvalid"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postAuthResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Đặt lại mật khẩu thành công */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginInvalid"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAuthCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token CSRF */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getUsersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thông tin user */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getUsersByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thông tin user */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session hợp lệ */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session đã revoke và cookie được clear */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["CsrfInvalid"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    patchUsersMePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequest"];
            };
        };
        responses: {
            /** @description Preference đã cập nhật */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postWalletBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletBaselineRequest"];
            };
        };
        responses: {
            /** @description Wallet đã khởi tạo */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            409: components["responses"]["WalletAlreadyInitialized"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getLedgerTransactions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                type?: components["schemas"]["TransactionType"];
                categoryId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger page */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postLedgerTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction đã commit */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            409: components["responses"]["IdempotencyConflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["DomainValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getLedgerTransactionsByTransactionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postLedgerTransactionsByTransactionIdCorrections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCorrectionRequest"];
            };
        };
        responses: {
            /** @description Correction đã commit */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["DomainValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getSavings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Savings */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getSavingsTransfers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Savings transfer page */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsTransferPageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postSavingsTransfers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSavingsTransferRequest"];
            };
        };
        responses: {
            /** @description Transfer đã commit */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsTransferResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            409: components["responses"]["IdempotencyConflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["DomainValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getCategories: {
        parameters: {
            query?: {
                appliesTo?: components["schemas"]["TransactionType"];
                includeDisabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category đã tạo */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    patchCategoriesByCategoryId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category đã cập nhật */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getBudgets: {
        parameters: {
            query: {
                /** @example 2026-09 */
                month: components["parameters"]["Month"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget list */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    putBudgetsByCategoryId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget đã cập nhật */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["DomainValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getBudgetsSummary: {
        parameters: {
            query: {
                /** @example 2026-09 */
                month: components["parameters"]["Month"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget summary */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getReportsMonthly: {
        parameters: {
            query: {
                /** @example 2026-09 */
                month: components["parameters"]["Month"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly report */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getReportsDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postIssues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue đã tạo */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getIssuesMe: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue page */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuePageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAdminIssues: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["IssueStatus"];
                priority?: components["schemas"]["IssuePriority"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin issue page */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuePageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAdminIssuesByIssueId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue detail */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    patchAdminIssuesByIssueId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue đã cập nhật */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    postAdminIssuesByIssueIdNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminNoteRequest"];
            };
        };
        responses: {
            /** @description Note đã tạo */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNoteResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAdminAuditLogs: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit page */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User statistics */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API đang chạy */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            default: components["responses"]["InternalError"];
        };
    };
    getHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency sẵn sàng */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
            default: components["responses"]["InternalError"];
        };
    };
}
